//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean PointingIndexLeft
        {
            get
            {
                return SteamVR_Actions.default_PointingIndexLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean PointingIndexRight
        {
            get
            {
                return SteamVR_Actions.default_PointingIndexRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClickA
        {
            get
            {
                return SteamVR_Actions.default_ClickA;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClickB
        {
            get
            {
                return SteamVR_Actions.default_ClickB;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClickX
        {
            get
            {
                return SteamVR_Actions.default_ClickX;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClickY
        {
            get
            {
                return SteamVR_Actions.default_ClickY;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGripLeft
        {
            get
            {
                return SteamVR_Actions.default_GrabGripLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGripRight
        {
            get
            {
                return SteamVR_Actions.default_GrabGripRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickLeft
        {
            get
            {
                return SteamVR_Actions.default_JoystickLeft;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickRight
        {
            get
            {
                return SteamVR_Actions.default_JoystickRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
